//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemZapisowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groups()
        {
            this.StudentEnrollmentLog = new HashSet<StudentEnrollmentLog>();
            this.StudentsGroups = new HashSet<StudentsGroups>();
        }
    
        public int GroupId { get; set; }
        public int CourseId { get; set; }
        public string Type { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public int DayId { get; set; }
        public string Teacher { get; set; }
        public int MaximumSeats { get; set; }
        public int OccupiedSeats { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Days Days { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentEnrollmentLog> StudentEnrollmentLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsGroups> StudentsGroups { get; set; }
    }
}
