//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemZapisowy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemZapisowyEntities : DbContext
    {
        public SystemZapisowyEntities()
            : base("name=SystemZapisowyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrators> Administrators { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Days> Days { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<FieldsOfStudy> FieldsOfStudy { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Semesters> Semesters { get; set; }
        public virtual DbSet<StudentEnrollmentLog> StudentEnrollmentLog { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<StudentsGroups> StudentsGroups { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<GroupsOfCoursesOverview> GroupsOfCoursesOverview { get; set; }
        public virtual DbSet<SemestersStudentsOverview> SemestersStudentsOverview { get; set; }
        public virtual DbSet<StudentsGroupsOverview> StudentsGroupsOverview { get; set; }
    }
}
