//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemZapisowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsGroups
    {
        public int StudentsGroupsId { get; set; }
        public decimal IndexNumber { get; set; }
        public int GroupId { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Students Students { get; set; }
    }
}
