//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemZapisowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.StudentEnrollmentLog = new HashSet<StudentEnrollmentLog>();
            this.StudentsGroups = new HashSet<StudentsGroups>();
        }
    
        public decimal IndexNumber { get; set; }
        public int FieldOfStudyId { get; set; }
        public int YearOfCollege { get; set; }
        public int SemesterId { get; set; }
        public int UserId { get; set; }
    
        public virtual FieldsOfStudy FieldsOfStudy { get; set; }
        public virtual Semesters Semesters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentEnrollmentLog> StudentEnrollmentLog { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsGroups> StudentsGroups { get; set; }
    }
}
