//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemZapisowy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsOfCoursesOverview
    {
        public string CourseName { get; set; }
        public string Type { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public string Teacher { get; set; }
        public int MaximumSeats { get; set; }
        public int OccupiedSeats { get; set; }
        public string DayName { get; set; }
        public string FieldOfStudyName { get; set; }
    }
}
