//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemZapisowy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemZapisowyEntities : DbContext
    {
        public SystemZapisowyEntities()
            : base("name=SystemZapisowyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FieldsOfStudy> FieldsOfStudies { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<StudentEnrollmentLog> StudentEnrollmentLogs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentsGroup> StudentsGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<GroupsOfCoursesOverview> GroupsOfCoursesOverviews { get; set; }
        public virtual DbSet<SemestersStudentsOverview> SemestersStudentsOverviews { get; set; }
        public virtual DbSet<StudentsGroupsOverview> StudentsGroupsOverviews { get; set; }
    }
}
