//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemZapisowy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemestersStudentsOverview
    {
        public string SemesterName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal IndexNumber { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public decimal PESEL { get; set; }
    }
}
